name: fdation
description: Dart foundation goods.
version: 1.0.0
homepage: https://github.com/andypangaribuan/fdation

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: ^1.8.0
  synchronized: ^3.0.0+3
  clock: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
